# Generated by Django 5.2.1 on 2025-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('material', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
